name: Build PR
on: [ pull_request ]
jobs:
  build_pr:
    if: github.repository_owner == 'IntellectualSites'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        jdk: [ 17, 21 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - name: Clean Build
        run: ./gradlew clean build
